# Visualization functions

In [1]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

## Load dataset

In [2]:
penguins_df = pd.read_csv("./data/processed/penguins_pca.csv")

display(penguins_df.head())

,Unnamed: 0,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_outlier,bill_depth_mm_outlier,flipper_length_mm_outlier,body_mass_g_outlier,is_any_outlier,body_mass_kg,bill_area_mm2,bill_ratio,flipper_mass_ratio,cluster,PC1,PC2
0,0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,Male,False,False,False,False,False,3.75,731.170,2.090909,48.266667,0,-1.847117,0.047075
1,1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,Female,False,False,False,False,False,3.80,687.300,2.270115,48.947368,0,-1.308894,-0.430261
2,2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,Female,False,False,False,False,False,3.25,725.400,2.238889,60.000000,0,-1.371586,-0.155611
3,3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,Unknown,False,False,False,False,False,4.05,768.985,2.569364,48.641975,2,-0.249892,0.101175
4,4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,Female,False,False,False,False,False,3.45,708.310,1.901554,55.942029,0,-1.882669,-0.003027

## Correlation Heatmap

In [3]:
corr_matrix = penguins_df.select_dtypes(include="float").corr().round(2)
corr_fig = px.imshow(corr_matrix, 
                     color_continuous_scale="RdBu",
                     zmin=-1, 
                     zmax=1, 
                     text_auto=True)
corr_fig

## Feature Histogram
* Dropdown: Select attributes
* Slider: Number of bins

In [4]:
def feat_histogram(df: pd.DataFrame, feature: str, nbins: int):
    fig = px.histogram(df, x=feature, nbins=nbins)
    return fig

## Distribution 
* Tick box: Species(All, Adelie, Chinstrap, Gentoo)

In [ ]:
def bar_species_island(df: pd.DataFrame):
    # Color theme
    color_map = {
        "Adelie": "darkorange",
        "Chinstrap": "purple",
        "Gentoo": "#008B8B"
    }

    count_df = df.groupby("island")["species"].value_counts().reset_index()
    count_df= count_df.sort_values(by="species")
    fig = px.bar(
        count_df, x="island", y="count", color="species",
        color_discrete_map = color_map
    )

    fig.update_layout(
        title={
            "text": ("Distribution of Species Among Islands<br>"
            "<span style='font-size:0.8em; color:gray;'>"
            "While Adele spreads across three islands, "
            "Chinstrap and Gentoo sticks to Dream and Biscoe respectively</span>"
        ),
        "x": 0
    }
    )
    return fig

In [43]:
bar_species_island(penguins_df)

## Correlation 
* Tick box: Species in scatterplot (All, Adelie, Chinstrap, Gentoo)
* Tick box: OLS (Yes, No)

In [44]:
def corr_flipper_body(df: pd.DataFrame):
    # Color theme
    color_map = {
        "Adelie": "darkorange",
        "Chinstrap": "purple",
        "Gentoo": "#008B8B"
    }
    
    fig = px.scatter(
        penguins_df,
        x="flipper_length_mm", y="body_mass_g",
        color="species", facet_col="island",
        color_discrete_map=color_map,
        trendline="ols",
        hover_data=['species', 'island', 'sex'],
        title="Flipper Length and Body Mass Per Island",
        # morphology is driven more by species than geography
        subtitle="All species show a positive relationship, " \
        "with Adelie remaining consistent across islands, " \
        "indicating morphology is driven more by species than geography."
    )

    fig.update_layout(template="plotly_white")
    return fig

In [42]:
corr_flipper_body(penguins_df)

In [63]:
def corr_bill_body(df: pd.DataFrame):
    # Color theme
    color_map = {
        "Adelie": "darkorange",
        "Chinstrap": "purple",
        "Gentoo": "#008B8B"
    }
    
    fig = px.scatter(
        penguins_df,
        x="bill_area_mm2", y="body_mass_g",
        color="species", facet_col="island",
        color_discrete_map=color_map,
        trendline="ols",
        hover_data=['species', 'island', 'sex']
    )

    fig.update_layout(
        template="plotly_white",
        title={
            "text": ("Bill Area and Body Mass Per Island<br>"
            "<span style='font-size:0.8em; color:gray;'>"
            "All species show a positive relationship, " \
        "with Adelie remaining consistent across islands, " \
        "indicating morphology is driven more by species than geography</span>"
        ),
        "x": 0,
        "xanchor": "left"
        },
        margin=dict(t=100),
    )
    
    return fig

In [64]:
corr_bill_body(penguins_df)

## How big is Body Mass to Bill Area

In [96]:
def box_body_bill_species(df):
    # Color theme
    color_map = {
        "Adelie": "darkorange",
        "Chinstrap": "purple",
        "Gentoo": "#008B8B"
    }
    
    df["mass_per_bill_area"] = (penguins_df["body_mass_g"] / (penguins_df["bill_length_mm"] * penguins_df["bill_depth_mm"]))

    fig = px.box(
        penguins_df,
        x="species",
        y="mass_per_bill_area",
        color="species",
        color_discrete_map={
        "Adelie": "darkorange",
        "Chinstrap": "purple",
        "Gentoo": "#008B8B"
        },
        title="Body Mass per Unit Bill Area by Species"
    )

    fig.update_layout(
    template="plotly_white",
    yaxis_title="Mass per Bill Area (g / mm²)"
    )

    return fig

In [98]:
box_body_bill_species(penguins_df)

In [97]:
def box_body_bill_island(df):
    # Color theme
    color_map = {
        "Adelie": "darkorange",
        "Chinstrap": "purple",
        "Gentoo": "#008B8B"
    }
    
    df["mass_per_bill_area"] = (penguins_df["body_mass_g"] / (penguins_df["bill_length_mm"] * penguins_df["bill_depth_mm"]))

    fig = px.box(
        penguins_df,
        x="island",
        y="mass_per_bill_area",
        color="island",
        color_discrete_map={
        "Adelie": "darkorange",
        "Chinstrap": "purple",
        "Gentoo": "#008B8B"
        },
        title="Body Mass per Unit Bill Area by Island"
    )

    fig.update_layout(
    template="plotly_white",
    yaxis_title="Mass per Bill Area (g / mm²)"
    )

    return fig

In [99]:
box_body_bill_island(penguins_df)

## Simpson's paradox when omitting the species variable
Expected: Filter general vs each species

In [67]:
def bill_length_depth(df: pd.DataFrame):
    
    fig = px.scatter(
        penguins_df,
        x="bill_length_mm", y="bill_depth_mm",
        hover_data=['species', 'island', 'sex'],
        color_discrete_sequence=["black"], trendline="ols",
        title="Penguin bills dimension"
    )

    fig.update_layout(template="plotly_white")
    return fig

In [68]:
bill_length_depth(penguins_df)

In [69]:
def bill_length_depth(df: pd.DataFrame):
    color_map = {
        "Adelie": "darkorange",
        "Chinstrap": "purple",
        "Gentoo": "#008B8B"
    }
    
    fig = px.scatter(
        penguins_df,
        x="bill_length_mm", y="bill_depth_mm",
        color="species", trendline="ols",
        color_discrete_map=color_map, 
        hover_data=['species', 'island', 'sex'],
        title="Penguin bills dimension"
    )

    fig.update_layout(template="plotly_white")
    return fig

In [70]:
bill_length_depth(penguins_df)

## Ground truth labels

In [71]:
def plot_pca_clusters(df):
    fig = px.scatter(
        df,
        x='PC1',
        y='PC2',
        color='cluster',
        hover_data=['species', 'island', 'sex'],
    )
    return fig

plot_pca_clusters(penguins_df)

In [72]:
def plot_pca_species(df):
    fig = px.scatter(
        df,
        x='PC1',
        y='PC2',
        color='species',
        title="Ground Truth (Species)"
    )

    return fig
plot_pca_species(penguins_df)

In [73]:
cluster_map = {
    0: "Adelie",
    1: "Gentoo",
    2: "Chinstrap"
}

penguins_df["cluster_label"] = penguins_df["cluster"].map(cluster_map)
penguins_df["is_mismatch"] = penguins_df["cluster_label"] != penguins_df["species"]

In [74]:
penguins_df

,Unnamed: 0,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_outlier,bill_depth_mm_outlier,...,body_mass_kg,bill_area_mm2,bill_ratio,flipper_mass_ratio,cluster,PC1,PC2,mass_per_bill_area,cluster_label,is_mismatch
0,0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,Male,False,False,...,3.75,731.170,2.090909,48.266667,0,-1.847117,0.047075,5.128766,Adelie,False
1,1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,Female,False,False,...,3.80,687.300,2.270115,48.947368,0,-1.308894,-0.430261,5.528881,Adelie,False
2,2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,Female,False,False,...,3.25,725.400,2.238889,60.000000,0,-1.371586,-0.155611,4.480287,Adelie,False
3,3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,Unknown,False,False,...,4.05,768.985,2.569364,48.641975,2,-0.249892,0.101175,5.266683,Chinstrap,True
4,4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,Female,False,False,...,3.45,708.310,1.901554,55.942029,0,-1.882669,-0.003027,4.870749,Adelie,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,339,Gentoo,Biscoe,44.45,17.3,197.0,4050.0,Unknown,False,False,...,4.05,768.985,2.569364,48.641975,2,-0.249892,0.101175,5.266683,Chinstrap,True
340,340,Gentoo,Biscoe,46.80,14.3,215.0,4850.0,Female,False,False,...,4.85,669.240,3.272727,44.329897,1,1.847583,-0.770313,7.247026,Gentoo,False
341,341,Gentoo,Biscoe,50.40,15.7,222.0,5750.0,Male,False,False,...,5.75,791.280,3.210191,38.608696,1,2.769939,0.289245,7.266707,Gentoo,False
342,342,Gentoo,Biscoe,45.20,14.8,212.0,5200.0,Female,False,False,...,5.20,668.960,3.054054,40.769231,1,1.728750,-0.706819,7.773260,Gentoo,False
343,343,Gentoo,Biscoe,49.90,16.1,213.0,5400.0,Male,False,False,...,5.40,803.390,3.099379,39.444444,1,2.036054,0.358217,6.721518,Gentoo,False

In [75]:
def plot_pca_clusters(df):
    fig = px.scatter(
        df,
        x='PC1',
        y='PC2',
        color='cluster_label',
        symbol='is_mismatch',  # 👈 key
        symbol_map={
            False: "circle",
            True: "x"
        },
        color_discrete_map={
            "Adelie": "darkorange",
            "Chinstrap": "purple",
            "Gentoo": "#008B8B"
        },
        title="PCA Clusters vs Ground Truth"
    )
    return fig

In [76]:
plot_pca_clusters(penguins_df)